### ISSUE TITLE
Poison and Water colours are too similar

### ISSUE THREAD

**Issue by Magnogen** [l2wilson94/PondOfFame#2]
I'm not sure if it's because I'm colourblind and can't tell the difference between them, or if it's because they are actually the same colour, but they're just so similar! I can barely tell them apart.

Maybe use a different purple colour for poison? Like `#9F40C2`?

**Comment by TodePond** [comment]
That's true! the pond of fame uses an old colour scheme. In the up-to-date one, they're more different: https://colour.todepond.cool/

When I make pond of fame 2.0 I'll update the colours!

**Comment by Magnogen** [comment]
Ooo nice! Looking forward to when that rolls out!

**Comment by TodePond** [comment]
they've been updated!
